name: Build test for SUMMA-Actors
on:
  #push:
  #  branches: [ main ]
  #pull_request:
  #  branches: [ main ]
  workflow_dispatch: # for manually triggered workflow

jobs:
  Check-Runner-Packages:
    name: Check Runner Packages
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - run: echo "Check Runner Packages"
      - run: gfortran --version    # check for gfortran compiler
      - run: g++ --version         # check for g++ compiler
      - run: curl --version        # check for curl
      - run: wget --version        # check for wget
  Install-LAPACK:
    name: Install LAPACK
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./utils/dependencies
    steps:
      - uses: actions/checkout@v4  # checkout SUMMA-Actors repo
      - run: echo "Install LAPACK"
      #- run: ./install_lapack.sh   # install LAPACK -- successful
  Install-NetCDF:
    name: Install NetCDF
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./utils/dependencies
    steps:
      - uses: actions/checkout@v4  # checkout SUMMA-Actors repo
      - run: echo "Install NetCDF"
      #- run: ./install_netcdf.sh   # install NetCDF -- possible errors
  Install-CAF:
    name: Install CAF
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./utils/dependencies
    steps:
      - uses: actions/checkout@v4  # checkout SUMMA-Actors repo
      - run: echo "Install CAF"
      #- run: ./install_caf.sh      # install CAF -- successful
  Install-SUNDIALS:
    name: Install SUNDIALS
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./utils/dependencies
    steps:
      - uses: actions/checkout@v4  # checkout SUMMA-Actors repo
      - run: echo "Install SUNDIALS"
      #- run: ./install_sundials.sh # install SUNDIALS -- successful
  Install-SUMMA:
    name: Clone SUMMA
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./build
    steps:
      - uses: actions/checkout@v4  # checkout SUMMA-Actors repo
      - run: echo "Clone SUMMA"
      - run: git clone -b develop_sundials https://github.com/CH-Earth/summa.git
