name: Build test for SUMMA-Actors
on:
  #push:
  #  branches: [ main ]
  #pull_request:
  #  branches: [ main ]
  workflow_dispatch: # for manually triggered workflow

jobs:
  Build-SUMMA-Actors:
    name: Build SUMMA-Actors
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./
    steps:
      - uses: actions/checkout@v4  # checkout SUMMA-Actors repo
      - run: echo "Check Runner Packages"
      - run: gfortran --version    # check for gfortran compiler
      - run: g++ --version         # check for g++ compiler
      - run: curl --version        # check for curl
      - run: wget --version        # check for wget
      - run: echo "Changing Directory to utils/dependencies"
      - run: cd ./utils/dependencies
      - run: echo "Install LAPACK"
      - run: ./install_lapack.sh   # install LAPACK
      
  #Check-Runner-Packages:
  #  name: Check Runner Packages
  #  runs-on: ubuntu-latest
  #  defaults:
  #    run:
  #      shell: bash
  #  steps:
  #    - uses: actions/checkout@v4  # checkout SUMMA-Actors repo
  #    - run: echo "Check Runner Packages"
  #    - run: gfortran --version    # check for gfortran compiler
  #    - run: g++ --version         # check for g++ compiler
  #    - run: curl --version        # check for curl
  #    - run: wget --version        # check for wget
  #Install-LAPACK:
  #  name: Install LAPACK
  #  runs-on: ubuntu-latest
  #  defaults:
  #    run:
  #      shell: bash
  #      working-directory: ./utils/dependencies
  #  steps:
  #    - uses: actions/checkout@v4  # checkout SUMMA-Actors repo
  #    - run: echo "Install LAPACK"
  #    - run: ./install_lapack.sh   # install LAPACK
  #Install-NetCDF:
  #  name: Install NetCDF
  #  runs-on: ubuntu-latest
  #  defaults:
  #    run:
  #      shell: bash
  #      working-directory: ./utils/dependencies
  #  steps:
  #    - uses: actions/checkout@v4  # checkout SUMMA-Actors repo
  #    - run: echo "Install NetCDF"
  #    - run: sudo apt install libcurl4-openssl-dev # install cURL development headers
  #    - run: ./install_netcdf.sh   # install NetCDF
  #Install-CAF:
  #  name: Install CAF
  #  runs-on: ubuntu-latest
  #  defaults:
  #    run:
  #      shell: bash
  #      working-directory: ./utils/dependencies
  #  steps:
  #    - uses: actions/checkout@v4  # checkout SUMMA-Actors repo
  #    - run: echo "Install CAF"
  #    - run: ./install_caf.sh      # install CAF
  #Install-SUNDIALS:
  #  name: Install SUNDIALS
  #  runs-on: ubuntu-latest
  #  defaults:
  #    run:
  #      shell: bash
  #      working-directory: ./utils/dependencies
  #  steps:
  #    - uses: actions/checkout@v4  # checkout SUMMA-Actors repo
  #    - run: echo "Install SUNDIALS"
  #    - run: ./install_sundials.sh # install SUNDIALS
  #Clone-SUMMA:
  #  name: Clone SUMMA
  #  runs-on: ubuntu-latest
  #  defaults:
  #    run:
  #      shell: bash
  #      working-directory: ./build
  #  steps:
  #    - uses: actions/checkout@v4  # checkout SUMMA-Actors repo
  #    - run: echo "Clone SUMMA"
  #    - run: git clone -b develop_sundials https://github.com/CH-Earth/summa.git
  #Build-SUMMA-Actors:
  #  name: Build SUMMA-Actors
  #  needs: [Check-Runner-Packages, Install-LAPACK, Install-NetCDF, Install-CAF, Install-SUNDIALS, Clone-SUMMA]
  #  runs-on: ubuntu-latest
  #  defaults:
  #    run:
  #      shell: bash
  #      working-directory: ./build/build_scripts
  #  steps:
  #    - uses: actions/checkout@v4  # checkout SUMMA-Actors repo
  #    - run: echo "Build SUMMA-Actors"
  #    - run: ./build.sh
